// Loading

export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING'

// Bug

export const GET_ALL_PROJECT_CATEGORY = 'GET_ALL_PROJECT_CATEGORY';

export const CREATE_NEW_PROJECT = 'CREATE_NEW_PROJECT';

export const GET_ALL_LIST_PROJECT = 'GET_ALL_LIST_PROJECT';

export const OPEN_DRAWER_MODAL = 'OPEN_DRAWER_MODAL';

export const CLOSE_DRAWER_MODAL = 'CLOSE_DRAWER_MODAL';

/*ACTION SAGA */

export const INFO_USER_LOGIN_SAGA = 'INFO_USER_LOGIN_SAGA';

export const GET_ALL_PROJECT_CATEGORY_SAGA = 'GET_ALL_PROJECT_CATEGORY_SAGA';

export const CREATE_NEW_PROJECT_SAGA = 'CREATE_NEW_PROJECT_SAGA';

export const GET_ALL_LIST_PROJECT_SAGA = 'GET_ALL_LIST_PROJECT_SAGA';